---
dockerlint:
  tags:
    - default
  image: vpgrp/nodejs:latest
  before_script:
    - npm install -g dockerlint
  script:
    - dockerlint Dockerfile

yamllint:
  tags:
    - default
  image: vpgrp/debian:stretch
  before_script:
    - >
      apt-get update -qq -y &&
      apt-get install -qq -y python3 python3-pkg-resources yamllint
  script:
    - yamllint .gitlab-ci.yml
    - yamllint docker-compose.yml

docker-compose:
  tags:
    - default
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm .
# EOF
